name: Docker image parse and scan
description: Parse Dockerfile and build, scan image if "blessed image" is not used
inputs:
  pathDockerfile:
    description: Path to Dockerfile
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # Check if one of the Appsec "blessed" images is used in Dockerfile
        if grep -wq "baseimage1\|baseimage2\|baseimage3\|baseimage4" ${{ inputs.pathDockerfile }} | tail -1 ; then 
          echo "This dockerfile is using appsec team blessed image, no need to scan"
        else
          # Build docker image
          echo "Building docker image ... "
          docker build --tag test-image:${{ github.sha }} .
          # Scan docker image with trivy, fail job if there is at least 1 critical
          echo "Scanning docker image ... "
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy --ignore-unfixed --exit-code 1 --severity CRITICAL test-image:${{ github.sha }}
        fi
