name: Docker image parse and scan
description: Parse Dockerfile and build, scan image if "blessed image" is not used
inputs:
  pathDockerfile:
    description: Path to Dockerfile
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # ---------------CHECK IF ONE OF BLESSED IMAGES IS USED--------------
        if grep -q ’baseimage1\|baseimage2\|baseimage3\|baseimage4’ ${{ inputs.pathDockerfile }} ; then 
          echo "This dockerfile is using appsec team blessed image, no need to scan"
        else
          # -------------BUILD DOCKER IMAGE----------------------------------
          echo "Building docker image ... "
          docker build --tag test-image:${{ github.sha }} .
          # -------------SCAN DOCKER IMAGE WITH TRIVY------------------------
          echo "Scanning docker image ... "
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$HOME"/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 1 --severity CRITICAL test-image:${{ github.sha }}
        fi
