name: dsp-appsec-trivy-example
on: [pull_request]

jobs:
  appsec-trivy:
    name: Parse Dockerfile and build, scan image if "blessed image" is not used
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./appsec-trivy-action
        with:
          pathDockerfile: ./Dockerfile # ADD DOCKERFILE PATH HERE
