name: dsp-appsec-trivy-example
on: [pull_request]

jobs:
  appsec-trivy:
    name: Parse Dockerfile and build, scan image if "blessed image" is not used
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          context: ./test               # (optional) set the path to Docker build context
