name: dsp-appsec-trivy-action-test
on:
  push:
    branches:
      - v1
  pull_request:
    branches:
      - v1

jobs:
  test:
    name: Test Trivy action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Trivy scan
        uses: ./
        with:
          context: ./test
          dockerfile: Dockerfile.trivy

      - name: Test a blessed base image
        uses: ./
        with:
          context: ./test
          dockerfile: Dockerfile.notrivy
