name: dsp-appsec-trivy-action-test
on:
  push:
    branches:
      - v1
  pull_request:
    branches:
      - v1

jobs:
  test:
    name: Test Trivy action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: '[test] Build & scan'
        uses: ./
        with:
          context: ./test
          dockerfile: Dockerfile.trivy

      - name: '[test] Skip a blessed base image'
        uses: ./
        with:
          context: ./test
          dockerfile: Dockerfile.notrivy

      - name: '[test] Include all severities'
        uses: ./
        with:
          severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      
      https://github.com/broadinstitute/dsp-appsec-trivy-action/blob/3bb6a17ab85a1e0218db2a429d3b3a08b23b544c/.github/workflows/trivy.yml#L21-L24
      
      - name: '[test] Generate Sarif output'
        uses: ./
        with:
          image: gcr.io/distroless/static
          sarif: trivy-results.sarif

      - name: '[test] Upload scan results to GitHub Security tab'
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif
