name: dsp-appsec-trivy-action-test
on: [pull_request]

jobs:
  test:
    name: Parse Dockerfile and build, scan image if "blessed image" is not used
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Trivy scan
        uses: .
        with:
          context: ./test
          dockerfile: Dockerfile.trivy

      - name: Test a blessed base image
        uses: .
        with:
          context: ./test
          dockerfile: Dockerfile.notrivy
