name: dsp-appsec-trivy-action-test
on:
  push:
    branches:
      - v1
  pull_request:
    branches:
      - v1

jobs:
  test:
    name: Test Trivy action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: [test] Build & scan
        uses: ./
        with:
          context: ./test
          dockerfile: Dockerfile.trivy

      - name: [test] Skip a blessed base image
        uses: ./
        with:
          context: ./test
          dockerfile: Dockerfile.notrivy

      - name: [test] Scan a pre-built image
        uses: ./
        with:
          image: gcr.io/distroless/static
