name: dsp-appsec-trivy
on: [pull_request]

jobs:
  appsec-trivy:
    name: Parse Dockerfile and build, scan image if "blessed image" is not used
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # simple case
      - uses: broadinstitute/dsp-appsec-trivy-action@v1

      # alternatively, if you need to customize the path to Dockerfile and/or build context
      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          context: ./docker               # (optional) set the path to Docker build context
          dockerfile: Dockerfile.alpine   # (optional) set the path to Dockerfile within build context
