name: dsp-appsec-trivy
on: [pull_request]

jobs:
  appsec-trivy:
    # Parse Dockerfile and build, scan image if a "blessed" base image is not used
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # simple case
      - uses: broadinstitute/dsp-appsec-trivy-action@v1

      # alternatively, if you need to customize the path to Dockerfile and/or build context
      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          context: .              # (optional) set the path to Docker build context
          dockerfile: Dockerfile  # (optional) set the path to Dockerfile within build context
      
      # alternatively, with all vulnerability severity levels
      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

      # alternatively, if you're using a pre-built Docker image (e.g. with Jib or Buildpacks)
      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          image: gcr.io/distroless/static

      # alernatively, if you'd like to upload results to GitHub Security tab
      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          image: gcr.io/distroless/static
          sarif: trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
